#!/usr/bin/perl -w

use strict;
use warnings;
use File::Basename;
use Cwd 'abs_path';

die "Usage:perl $0 <metadata>" if(@ARGV != 1);

my ($config )       = @ARGV;

my %metadata        = ();
profile();

my  $project_home   =  abs_path($metadata{project_home}) . qq{/$metadata{project_id}/rank_abundance};

my  $report         =  qq{$project_home/report};
my  $runs           =  qq{$project_home/runs};

my  $datasets       =  abs_path($metadata{project_home}) . qq{/$metadata{project_id}/classify/zotus};

my  $utils          =  dirname( abs_path($0) ) . '/../utils';
my  $binaries       =  dirname( abs_path($0) ) . '/../binaries';

my  $dry_run        =  0;
    $dry_run        =  1 if(exists $metadata{dry_run} && $metadata{dry_run} eq 'T');

submit();
exit;

sub submit{

    make_fs();
    rank_abundance_run();

}

sub profile {

    open( PROFILE,  $config ) || die "[ERR]: can't open $config $!\n";
    while(<PROFILE>){

        $_ =~ s/\s+$//;  
        next if(/^#/ || !/^\S+/);
        my ($key, $value)  = split /\s+/, $_, 2;
        $metadata{ $key } = $value;

    } 
    close PROFILE;

}

sub make_fs {
    
    my $cmd = qq{mkdir -p $report  \
                          $runs};
       $cmd =~ s/\n\s+/ /msg;
    system $cmd;
}


sub rank_abundance_run {
    
    my $sh = qq{$runs/rank_abundance.sh};    
    open(EXPORT, qq{>$sh} ) || die "[ERR]: can't open $sh $!";
    
	print EXPORT rank_abundance();
    print EXPORT utils();
    
    close EXPORT;
    system qq{cat $sh | $binaries/gargs -v --nlines 1 -p 1 "{}"\n} if(!$dry_run);
}

sub rank_abundance {
  
   my $cmd  = qq{$utils/rank_abundance.R             \
                   $datasets/zotu_table_norm.txt     \
                   $report/rank_abundance.pdf ;\n};
      $cmd  =~ s/\s+\n\s+/ /msg;
   return $cmd;

}

sub utils {

    my  $cmd = qq{$utils/pdf2png $report/rank_abundance.pdf ;\n};
    return $cmd;

}